### ISSUE TITLE
[JOSS review assistance] Timeseries expected energy models

### ISSUE THREAD

**Issue by williamhobbs** [sandialabs/pvOps#77] opened 2023-09-21 15:52 UTC
- The `iec_calc` model is described as being "based on IEC calculations" and using "IEC standards" in https://pvops.readthedocs.io/en/latest/pages/moduleguides/timeseries.html#module-overview and elsewhere. It looks like a simple performance ratio. A few suggestions:
  - mention which IEC standard/model is is based on
  - clarify in docs (e.g., https://pvops.readthedocs.io/en/latest/pages/apidoc/timeseries.html#module-pvops.timeseries.models.iec) that it needs *plane of array* irradiance as an input (assuming that is the case)
  - Make at least a brief reference to potential downsides/limitations of a simple model like this, e.g., when temperature is ignored. 
- As far as I can tell, none of the models make use of temperature data (either back of module temp or the combo of ambient temp and wind speed) based on their own documentation. I would suggest adding this, or at least documenting why it isn't necessary. I would worry that someone like a performance engineer that is new to solar could start with this package and then assume that irradiance is all that really matters. I *do* see ambient temperature and wind speed passed in some of the examples, but it isn't clear to me if/how they are being used (for example, wind_speed_ms is commented out in the dynamic linear modeling example in tutorial_timeseries.ipynb). 
- Similar to the last point, AC capacity might be useful. If the AIT or linear model tool can estimate AC capacity on their own, this should probably be mentioned in the docs. 
- A comparison of the structure of these models with something like a pvwatts-style model, or PVUSA/ASTM regression, would be helpful.

**Comment by williamhobbs** [comment] 2023-10-02 16:55
After thinking about this some more, I suggest significant updates to the expected energy modeling capabilities, or leaving this part of pvOps out. Unless I'm misunderstanding the AIT or linear models, I don't think these are consistent with industry best-practices, and could confuse performance engineers that are new to solar.

**Comment by MichaelHopwood** [comment] 2023-10-05 23:59
Thanks @williamhobbs! As you've discovered, one of the main purposes of the timeseries section is to provide access to timeseries modeling methods for photovoltaic system performance. And as you're probably aware, the IEC standard denotes formulas that practitioners can use to effectively model the performance of their system based off the site's capacity, and the irradiance conditions, among other information (based off which IEC formula you're looking at specifically). The point of the linear models is to render a model that is more accurate (experimentally proven, see below) using the same information that the IEC formula uses, with no extra information required.

For more information, you can see our open-access journal paper available here: https://www.mdpi.com/2076-3417/12/4/1872
Here's a plot from the paper that shows the linear method has reduced bias compared to the IEC model.
![image](https://github.com/sandialabs/pvOps/assets/37667642/b4e562a4-803a-4f95-b1fa-d837f507354d)

@kbonney maybe you can address some of the documentation improvements recommended above. I've provided some information below (same bullet points ordering as presented in question) :
* iec 61724-1
* Plane-of-array irradiance is recommended if you're going to be using our pre-trained AIT model, but if you're training your own model using our medley of model options (easily accessible using `pvops.timeseries.models.linear.modeller`)
* For our AIT model we only had marginal effects from using wind speed - these effects were beneficial on some sites and detrimental on other sides - likely based on temperature sensor uncertainty or poor precision. Given the gains we see using linear regression models like the ones configured here, it seems like very low hanging fruit for many practitioners to use inplace of the IEC standard formula, and it is reliable compared to the determinstic properties of many machine learning algorithms. Still, the future work of this section is to incorporate or if we need to, pioneer, timeseries methods that are even more accurate than this simple baseline model. It's also worth mentioning that **if the user wants to have linear models that use temperature or wind speed signals, they can train their own models easily using the `modeller` mentioned above.
* Teams can use AC energy if they want to train an AC energy modeler.
* I was once familiar with these methods but have since forgot, @kbonney feel free to address these if you have the bandwidth but I don't expect this is a blocking issue

**Comment by williamhobbs** [comment] 2023-10-11 19:02
In my opinion, the performance ratio in `iec_calc` is too simple to be used for plant performance assessments in a utility-scale plant operations/performance engineering application. The linear model does look relatively good in comparison, but it is hard to know how good it is in an absolute sense if it is not compared with a model that includes temperature effects and inverter clipping. 

> Teams can use AC energy if they want to train an AC energy modeler.

I think this is in response to my comment about AC capacity. I was referring to inverter and/or plant power limits that can result in "clipping" of plant output.

**Comment by kbonney** [comment] 2023-10-24 21:30
Addressed in #85 
- Added specific IEC standard to docs
- Clarified where plane of array irradiance is needed.

**Closed by kbonney** 2023-10-24 21:30 UTC
